# Generated by Django 2.2.3 on 2020-07-29 11:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='收货人姓名')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('phone', models.CharField(max_length=11, verbose_name='手机')),
                ('sign', models.CharField(max_length=50, null=True, verbose_name='标志建筑')),
                ('email', models.CharField(max_length=50, null=True, verbose_name='邮箱')),
                ('code', models.IntegerField(verbose_name='邮政编码')),
                ('isDefault', models.IntegerField(default='', verbose_name='默认地址')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户外键')),
            ],
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Product', verbose_name='商品id')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('cost', models.FloatField(default='', verbose_name='总消费')),
                ('number', models.CharField(default='', max_length=255, verbose_name='订单号')),
                ('quantity', models.IntegerField(verbose_name='购买数量')),
                ('addressId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.Address', verbose_name='用户地址')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Product', verbose_name='商品id')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
        ),
    ]
