# Generated by Django 2.2.3 on 2020-07-27 12:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=None, max_length=255, verbose_name='地址')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('isDefault', models.IntegerField(default=None, max_length=2, verbose_name='默认地址')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户外键')),
            ],
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Product', verbose_name='商品id')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户id')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('cost', models.FloatField(default=None, verbose_name='总消费')),
                ('number', models.CharField(default=None, max_length=255, verbose_name='订单号')),
                ('quantity', models.IntegerField(max_length=10, verbose_name='购买数量')),
                ('addressId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.Address', verbose_name='用户地址')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Product', verbose_name='商品id')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='用户id')),
            ],
        ),
    ]
