# Generated by Django 2.2.3 on 2020-07-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': '地址', 'verbose_name_plural': '地址'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='userfav',
            options={'verbose_name': '收藏', 'verbose_name_plural': '收藏'},
        ),
    ]
