# Generated by Django 2.2.3 on 2020-07-30 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200730_1544'),
        ('usercenter', '0002_auto_20200730_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='address',
            name='isDefault',
            field=models.BooleanField(default=False, verbose_name='默认地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='购买数量')),
                ('cost', models.FloatField(default='', verbose_name='每类商品的总价格')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.Order', verbose_name='订单id')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Product', verbose_name='商品id')),
            ],
            options={
                'verbose_name': '订单详情',
                'verbose_name_plural': '订单详情',
            },
        ),
    ]
