# Generated by Django 2.2.13 on 2020-07-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginName', models.CharField(max_length=25, verbose_name='登录名')),
                ('nickName', models.CharField(max_length=25, null=True, verbose_name='昵称')),
                ('password', models.CharField(max_length=25, verbose_name='密码')),
                ('sex', models.IntegerField(default=1, max_length=1, verbose_name='性别1为男0为女')),
                ('idcard', models.CharField(default=None, max_length=20, verbose_name='身份证')),
                ('email', models.CharField(default=None, max_length=80, verbose_name='邮箱')),
                ('mobile', models.IntegerField(default=None, max_length=11, verbose_name='手机号')),
                ('time', models.DateTimeField(default=None, verbose_name='登录时间')),
                ('score', models.IntegerField(default=0, max_length=11, verbose_name='积分')),
            ],
        ),
    ]
