# Generated by Django 2.2.13 on 2020-07-28 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=80, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='idcard',
            field=models.CharField(default='请填写身份证号', max_length=20, null=True, verbose_name='身份证'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.IntegerField(default=0, max_length=11, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 21, 48, 35, 976880), verbose_name='登录时间'),
        ),
    ]
