# Generated by Django 2.2.3 on 2020-07-30 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200729_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 30, 10, 36, 14, 395424)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登录时间'),
        ),
    ]
