# Generated by Django 2.2.13 on 2020-07-28 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200728_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.BigIntegerField(default=0, max_length=11, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 28, 22, 44, 45, 951387), verbose_name='登录时间'),
        ),
    ]
