# Generated by Django 2.2.3 on 2020-07-30 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200730_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverify',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 30, 15, 44, 2, 688834)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nickName',
            field=models.CharField(default='易买网用户', max_length=25, null=True, verbose_name='昵称'),
        ),
    ]
