# Generated by Django 2.2.5 on 2020-08-03 17:36
# Generated by Django 2.2.3 on 2020-08-03 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='商品数量')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Product', verbose_name='商品id')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
    ]
