# Generated by Django 2.2.3 on 2020-07-30 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_userid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': '购物车', 'verbose_name_plural': '购物车'},
        ),
    ]
